title: Areeba's Blog
description: CSSE Tri 3
owner_name: Areeba Ahmed
github_username: areeba-ahmed
github_repo: "areeba-tri-3"
baseurl: "/areeba-tri-3"
future: true
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/areeba-ahmed"}
    - { platform: spotify, user_url: "https://open.spotify.com/user/lgqzecuxrzdb0xw1rm7g2xehm?si=af2dcdd385234fd0" }      
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.html


